#General
name: iBank
main: com.iBank.iBank
version: ${project.version}(${buildNumber})[${version.snap}]{${version.codename}}
commands:
     bank:
       description: Manage your money
       usage: /bank help
     ibank:
       description: Manage your money
       usage: /ibank help
depend: [Vault]
#Generator
description: Banks for iConomy
maintainer: steffengy
authors: [steffengy]
# Add superperms !!
